{% set name = "tensorboard" %}
{% set version = "2.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl
  sha256: 107ca4821745f73e2aefa02c50ff70a9b694f39f790b11e6f682f7d326745eab

build:
  number: 0
  noarch: python
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - absl-py >=0.4
    - grpcio >=1.48.2
    - markdown >=2.6.8
    - numpy >=1.12.0
    - packaging
    - six >1.9
    - protobuf >=3.19.6,!=4.24.0
    - werkzeug >=1.0.1
    - setuptools >=41.0.0
    - tensorboard-data-server >=0.7.0,<0.8.0

test:
  requires:
    - pip
  imports:
    - tensorboard
  commands:
    - tensorboard -h
    - pip check

about:
  home: https://github.com/tensorflow/tensorboard
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: TensorFlow's Visualization Toolkit

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - mdraw
    - jschueller
    - xhochy
    - ngam
