{% set name = "tensorboard" %}
{% set version = "2.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl
  sha256: 263b909a2009cb3a79daa6abe64c1785cc317c25a54e4db2fecb6429ffc54c58

build:
  number: 0
  noarch: python
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - six >=1.9
    - numpy >=1.12.0
    - protobuf >=3.19.6
    - werkzeug >=1.0.1
    - markdown >=2.6.8
    - absl-py >=0.4
    - grpcio >=1.48.2
    - google-auth >=1.6.3,<3
    - google-auth-oauthlib >=0.5,<2
    - requests >=2.21.0,<3
    - setuptools >=41.0.0
    - tensorboard-data-server >=0.7.0,<0.8.0

test:
  requires:
    - pip
  imports:
    - tensorboard
  commands:
    - tensorboard -h
    - pip check

about:
  home: https://github.com/tensorflow/tensorboard
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: TensorFlow's Visualization Toolkit

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - mdraw
    - jschueller
    - xhochy
    - ngam
