{% set version = "2.0.0" %}
{% set build_number = 0 %}

package:
  name: tensorboard
  version: {{ version }}

source:
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl
  sha256: d3559616ccad8d72e7a259bff51be61a9bf1e66e2cebdc782c33e4b588b5e943

build:
  number: {{ build_number }}
  skip: True  # [win]
  script:
    - python -m pip install --no-deps --ignore-installed ./tensorboard-{{ version }}-py3-none-any.whl
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  # See: https://pypi.org/project/tensorboard
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.12.0
    - protobuf >=3.6.0
    - werkzeug >=0.11.15
    - markdown >=2.6.8
    - setuptools >=41.0.0
    - wheel >=0.26
    - six >=1.10.0
    - absl-py >=0.4
    - grpcio >=1.6.3

    #
    # After splitting out of tensorflow, the tensorboard pypi package is problematic:
    #
    #  - tensorflow does not need tensorboard to work
    #    (but depends on it, just to avoid surprising the users that were used to have tensorboard in the package)
    #
    #  - tensorboard does need tensorflow to work
    #    (but does not depend on it explicitly to avoid cyclical dependencies)
    #
    # This means that the tensorboard package is not standalone and should always be installed
    # by installing tensorflow. At the moment we are mirroring in conda-forge the wrongs on
    # pypi.
    #
    # Also note that this makes the noarch nature of the package a bit of a wishful thinking
    # (we can use tensorboard only on platforms with a tensorflow package available).
    #
    # See:
    #  Issue in TB tracker: https://github.com/tensorflow/tensorboard/issues/410
    #  Initial recipe PR: https://github.com/conda-forge/staged-recipes/pull/3866
    #  Issue in the TF recipe: https://github.com/conda-forge/tensorflow-feedstock/issues/42
    #
    # An alternative solution would be to uncomment the tensorflow dependency down here
    # and remove the tensorflow dependency on the tensorboard package. Pros: this would create
    # a saner dependency cycle. Cons: it would be inconsitent with the official pypi releases.
    #
    # - tensorflow >=1.4.0
    #

test:
  imports:
    - tensorboard
  # N.B. CLI tests are in the tensorflow package recipe (to avoid having an explicit circular dependency)
  # To be super-strict, we should run the original tests with bazel against the newly created package

about:
  home: https://github.com/tensorflow/tensorboard
  license: Apache 2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "TensorFlow's Visualization Toolkit"

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - dougalsutherland
    - roccqqck
