{% set version = "2.1.0" %}
{% set build_number = 0 %}

package:
  name: tensorboard
  version: {{ version }}

source:
  url: https://pypi.io/packages/py2/t/tensorboard/tensorboard-{{ version }}-py2-none-any.whl  # [py2k]
  sha256: 1c80eb17c9d4f2609ed11b9446f8168973f5bb7789a97e56e766a89e062a00b9  # [py2k]
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-{{ version }}-py3-none-any.whl  # [py3k]
  sha256: e6e64ec1e1500cc963b300895258f9605032c3a18bb40f95f2b3b12be16ff2f2  # [py3k]

build:
  number: {{ build_number }}
  skip: True  # [win and py27]
  script:
    - python -m pip install --no-deps --ignore-installed ./tensorboard-{{ version }}-py2-none-any.whl  # [py2k]
    - python -m pip install --no-deps --ignore-installed ./tensorboard-{{ version }}-py3-none-any.whl  # [py3k]
  entry_points:
    - tensorboard = tensorboard.main:run_main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - wheel >=0.26
    - numpy >=1.12.0
    - six >=1.10.0
    - protobuf >=3.4.0
    - werkzeug >=0.11.10
    - markdown >=2.6.8
    - absl-py >=0.8.0
    - grpcio >=1.6.3
    - futures >=3.1.1   # [py27]

test:
  imports:
    - tensorboard
  commands:
    - tensorboard -h

about:
  home: https://github.com/tensorflow/tensorboard
  license: Apache 2.0
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: "TensorFlow's Visualization Toolkit"

extra:
  recipe-maintainers:
    - sdvillal
    - gilbertfrancois
    - farhantejani
    - dougalsutherland
    - mdraw
