travis:
  secure:
    BINSTAR_TOKEN: twFvN7EZFhBv6olyf6nCZTwrUVo9sBYRwX+cAcxY5smmsNR8ROjousocEcPFVE8AZ+PjH56vFNkIq2MJIplirgjoRjSWYoqeYq2T7+VtPp5s77Kc8XvBjuQtDoWc/MaasuqhrdgGS6rHMfpR5/mt+pfNxHbsTPz955EvZAbFp1ezOJ+o65WHCkegSuNS6pnLTnU6/WNpLfRrwK54UapDW+ufUfoBdvbC2hStaczr1/tNk/becDbTOv9EpA1utJD6p1KQxh169oSkQ8CY0MPvObRq+bpYpHFZ/bacATP6jisFBvZr24vIv2d/iQyn5/iAeA7TlORHJE6AWY9XGihLTgWtezJRvj20BYapTMjHwEcZhAC60FgVrM7nHgNDCAKkboiBDxf6HlTtL7F/ew7pR2lU+mKEPldMA8FOi8ix76fvUiPQ2fmpqOMXG4UUobpX9qDzTifY5JP9fjBaXs0G25mV9jz1pE5lC39sx+sVF9ugXIF1wc+9rcgxMisZgEXgtKBXxWCeuPBtb4et/s8JshgVNji2kZjJARG06rmNWrqAHSXAjM90Cu50l+VRpljJZUdOOB+SOGjt99IGhWxft+I6yYLPLT3BGQUMXNUZxpUL/xssgxqddF5AvD7i6VAoI/mBRzGluBzLxS73KupPyDN/Mt9kWg4AH3OnPxw0GQU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
